run upstream velero ci against downstream
fusor/velero pull request #230
Opened 2022-11-11 17:50 UTC by weshayutin

seeing if running upstream ci against our downstream copy is valuable. /hold for now.

2022-12-02 20:10 UTC, weshayutin commented
oops.  git commit -m "looks like we need `make update` before make ci`" -s

2022-12-02 20:17 UTC, kaovilai requested changes

2022-12-02 20:17 UTC, kaovilai commented on .travis.yml
> +      make ci
```suggestion
      make update ci
```

2022-12-09 15:17 UTC, dymurray approved these changes
LGTM

2022-12-09 15:21 UTC, kaovilai approved these changes

2022-12-09 18:12 UTC, kaovilai commented
There's 8 commits here. Could you rebase/squash?

2022-12-09 18:16 UTC, weshayutin commented
@kaovilai there is a squash and merge option.. why not just use that?

2022-12-09 18:18 UTC, kaovilai commented
I'm ok with that usually. I'm concerned here that the commits in this PR include commits you did not author. Double check that you're using the right branch for this PR to merge into.
> [dymurray](https://github.com/dymurray) and others added 5 commits [last month](https://github.com/openshift/velero/pull/230#commits-pushed-43b816d)

2022-12-09 18:51 UTC, weshayutin commented
@kaovilai ya. it just needed to be rebased and squashed..

2022-12-13 19:52 UTC, sseago approved these changes

2024-02-22 15:46 UTC, kaovilai commented
/remove-lifecycle rotten

2024-10-18 20:52 UTC, closed without merging